# Generated by Django 5.2.4 on 2025-08-04 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Mensaje Privado de Usuarios', 'verbose_name_plural': 'Mensajes Privados de Usuarios'},
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='leido',
            new_name='is_leido',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos_usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados_usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
