# Generated by Django 5.2.4 on 2025-07-26 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0002_receta_imagen'),
        ('usuarios', '0002_perfil_permitir_mensajes_privados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Favorito',
                'verbose_name_plural': 'Categorías de Favoritos',
                'unique_together': {('user', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RecetaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='usuarios.categoriafavorita')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta Favorita',
                'verbose_name_plural': 'Recetas Favoritas',
                'unique_together': {('user', 'receta')},
            },
        ),
    ]
