# Generated by Django 5.2.4 on 2025-07-30 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Título de la Categoría')),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, help_text='Se generará automáticamente a partir del título.', max_length=100, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias_imagenes/', verbose_name='Imagen de la Categoría')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas_imagenes/')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_preparacion', models.IntegerField(blank=True, help_text='En minutos', null=True)),
                ('porciones', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='¿Receta de la Semana?')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_creadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='recetas_app.categoria')),
            ],
            options={
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Preparación de la salsa, Cocción de la pasta', max_length=200)),
                ('descripcion', models.TextField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='recetas_app.receta')),
            ],
            options={
                'verbose_name_plural': 'Pasos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=50)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='recetas_app.receta')),
            ],
            options={
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_hechos', to=settings.AUTH_USER_MODEL)),
                ('respuesta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='recetas_app.comentario')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='recetas_app.receta')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecetaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recetas Favoritas',
                'unique_together': {('usuario', 'receta')},
            },
        ),
    ]
