# Generated by Django 5.2.4 on 2025-08-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0002_mensaje'),
        ('usuarios', '0002_alter_mensaje_options_rename_leido_mensaje_is_leido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetafavorita',
            options={},
        ),
        migrations.AddField(
            model_name='recetafavorita',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_favoritas_en_categoria', to='usuarios.categoriafavorita'),
        ),
        migrations.AlterField(
            model_name='recetafavorita',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
