# Generated by Django 5.2.4 on 2025-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0002_categoria_receta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(blank=True, help_text='Número de porciones', null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True),
        ),
    ]
