# Generated by Django 5.2.4 on 2025-08-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0003_alter_recetafavorita_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
        migrations.AddField(
            model_name='categoria',
            name='fa_icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clase de Ícono de Font Awesome'),
        ),
    ]
