# Generated by Django 5.2.4 on 2025-07-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0004_alter_categoria_options_categoria_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='recetas_app.categoria'),
        ),
    ]
