# Generated by Django 5.2.4 on 2025-07-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0005_alter_receta_options_alter_comentario_autor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paso',
            options={'ordering': ['id'], 'verbose_name_plural': 'Pasos'},
        ),
        migrations.RemoveField(
            model_name='paso',
            name='orden',
        ),
        migrations.AddField(
            model_name='paso',
            name='titulo',
            field=models.CharField(default='', help_text='Ej: Preparación de la salsa, Cocción de la pasta', max_length=200),
            preserve_default=False,
        ),
    ]
